service: delivery-serverless-aws

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  environment:
    REGION: ${self:provider.region}
    PENDING_ORDERS_QUEUE:
      Ref: PendingOrdersQueue
    PENDING_ORDERS_QUEUE_NAME: PendingOrdersQueue
  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:${self:provider.region}:*:${self:provider.environment.PENDING_ORDERS_QUEUE_NAME}"

functions:
  makeOrder:
    handler: handler.makeOrder
    events:
      - http:
          method: post
          path: order

resources:
  Resources:
    PendingOrdersQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "${self:provider.environment.PENDING_ORDERS_QUEUE_NAME}"