service: delivery-serverless-aws

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  environment:
    REGION: ${self:provider.region}
    PENDING_ORDERS_QUEUE:
      Ref: PendingOrdersQueue
    PENDING_ORDERS_QUEUE_NAME: PendingOrdersQueue
  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:${self:provider.region}:*:${self:provider.environment.PENDING_ORDERS_QUEUE_NAME}"

functions:
  makeOrder:  # AWS Lambda
    handler: handler.makeOrder
    events:
      - http: # API Gateway
          method: post
          path: order
  prepareOrder:
    handler: handler.prepareOrder
    events:
      - sqs:
          arn: # Amazon Resource Name
            Fn::GetAtt:
              - PendingOrdersQueue
              - Arn
          batchSize: 1 

resources:
  Resources:
    PendingOrdersQueue: # SQS Queue Name
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "${self:provider.environment.PENDING_ORDERS_QUEUE_NAME}"