service: delivery-serverless-aws

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

functions:
  makeOrder:
    handler: handler.makeOrder
    events:
      - http:
          method: post
          path: order
